userno: your AIPS userno
workspace: your/workspace
idifits: your/data.idifits
exp_name: your experiment name
indisk: your disk number
eop_path: your eop file path
ionex_dir: your ionex map file directory
auto_ref_ant: determine reference antenna automatically for VLBA. True or False
ref_ant: two-charactor antenna code, e.g, PT
predef_source_list: your pre-defined source list. context file of previous sessions can be used
max_depth: 5
max_ang_v: 700.0
min_z: 0.7
kalman_factor: 0.08
smo_half_window: 5
weight: 0.4
cellsize: 0.0005
imsize: 128
niter: 500
gain: 0.1
ltype: -4
uvwtfn: ''
jmfit: True
