userno: your AIPS userno
workspace: your/workspace
idifits: your/data.idifits
exp_name: your experiment name
indisk: your disk number
eop_path: your eop file path
ionex_dir: your ionex map file directory
auto_ref_ant: determine reference antenna automatically for VLBA. True or False
ref_ant: two-charactor antenna code, e.g, PT
predef_source_list: your pre-defined source list. context file of previous sessions can be used
kalman_factor: 1.0e-14
rts_smoothing: True
viterbi_integer_states: 3
viterbi_max_jump: 1
viterbi_jump_penalty: 25.0
viterbi_huber_c: 3.0
viterbi_z_out: 4.0
cellsize: 0.0005
imsize: 128
niter: 500
gain: 0.1
ltype: -4
uvwtfn: ''
jmfit: True
